#!/usr/bin/env python3
"""SDXL daemon — generated by daemon_builder."""

import json
import os
import sys
import time
from datetime import datetime

import torch
from diffusers import StableDiffusionXLPipeline

_ML = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ML, "daemon"))

import config
from daemon_builder import run_daemon


def setup():
    model_id = config.get("model", "stabilityai/stable-diffusion-xl-base-1.0")
    pipe = StableDiffusionXLPipeline.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        use_safetensors=True,
        variant="fp16",
    )
    pipe.enable_model_cpu_offload()
    pipe.enable_vae_slicing()
    pipe.enable_vae_tiling()
    output_dir = os.path.expanduser(config.get("output_dir", "~/Pictures/generate"))
    os.makedirs(output_dir, exist_ok=True)
    return {"pipe": pipe, "output_dir": output_dir}


def handle_client(conn, state, bus):

    data = conn.recv(65536).decode()
    bus.emit("sdxl.read_done", bytes=len(data))

    msg = json.loads(data)
    bus.emit("sdxl.parse_done")

    prompt = msg.get("prompt", "")
    neg = msg.get("negative", "blurry, low quality, ugly")
    steps = msg.get("steps", 25)

    bus.emit("sdxl.generate_start", prompt=prompt, steps=steps)

    image = state["pipe"](
        prompt=prompt,
        negative_prompt=neg,
        num_inference_steps=steps,
    ).images[0]

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe = "".join(c if c.isalnum() or c in " _-" else "_" for c in prompt)[:60]
    fname = f"{ts}_{safe}.png"
    path = os.path.join(state["output_dir"], fname)
    image.save(path)
    print(f"[sdxl] saved {path}", flush=True)

    bus.emit("sdxl.generate_done", prompt=prompt, path=path, steps=steps)

    # Send response (builder handles any send errors)
    conn.sendall(json.dumps({"path": path}).encode())
    # No close, no finally, no exception handling!


if __name__ == "__main__":
    run_daemon(
        "SDXL",
        default_socket="/tmp/sdxl-daemon.sock",
        setup=setup,
        handle_client=handle_client,
        # max_connection_duration=300.00 # 5 minutes per request
    )
