#!/usr/bin/env python3
"""SDXL daemon — generated by daemon_builder."""

import json
import os
import sys
import time
from datetime import datetime

import torch
from diffusers import StableDiffusionXLPipeline

_ML = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_ML, "daemon"))
sys.path.insert(0, os.path.join(_ML, "monitor"))

import config
from daemon_builder import run_daemon


def setup():
    t0 = time.time()
    pipe = StableDiffusionXLPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0",
        torch_dtype=torch.float16,
        use_safetensors=True,
        variant="fp16",
    )
    pipe.enable_model_cpu_offload()
    pipe.enable_vae_slicing()
    pipe.enable_vae_tiling()
    print(f"SDXL loaded in {time.time() - t0:.1f}s", flush=True)

    output_dir = os.path.expanduser(config.get("output_dir", "~/Pictures/generate"))
    os.makedirs(output_dir, exist_ok=True)

    return {"pipe": pipe, "output_dir": output_dir}


def handle_client(conn, state, bus):
    if bus:
        bus.emit("sdxl.connection_open")

    try:
        data = conn.recv(65536).decode()
        msg = json.loads(data)
        prompt = msg.get("prompt", "")
        neg = msg.get("negative", "blurry, low quality, ugly")
        steps = msg.get("steps", 25)

        if bus:
            bus.emit("sdxl.generate_start", prompt=prompt, steps=steps)

        image = state["pipe"](
            prompt=prompt,
            negative_prompt=neg,
            num_inference_steps=steps,
        ).images[0]

        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe = "".join(c if c.isalnum() or c in " _-" else "_" for c in prompt)[:60]
        fname = f"{ts}_{safe}.png"
        path = os.path.join(state["output_dir"], fname)
        image.save(path)

        if bus:
            bus.emit("sdxl.generate_done", prompt=prompt, path=path, steps=steps)

        conn.sendall(json.dumps({"path": path}).encode())
    except Exception as e:
        try:
            conn.sendall(json.dumps({"error": str(e)}).encode())
        except Exception:
            pass
    finally:
        if bus:
            bus.emit("sdxl.connection_close")
        conn.close()


if __name__ == "__main__":
    run_daemon(
        "SDXL",
        default_socket="/tmp/sdxl-daemon.sock",
        default_event_socket="/tmp/sdxl-events.sock",
        setup=setup,
        handle_client=handle_client,
    )
