#!/usr/bin/env python3
"""STT daemon — generated by daemon_builder."""

import json
import os
import socket
import sys
import time

import numpy as np

_DIR = os.path.dirname(os.path.abspath(__file__))
_ML = os.path.dirname(_DIR)
sys.path.insert(0, _DIR)
sys.path.insert(0, os.path.join(_ML, "daemon"))

import config
from daemon_builder import run_daemon
from model import load_engine

SAMPLE_RATE = 16000


def setup():
    engine = load_engine(
        model_size=config.get("model_size"),
        device=config.get("device"),
        compute_type=config.get("compute_type"),
        beam_size=config.get("beam_size"),
    )
    return {
        "engine": engine,
        "max_buffer_samples": config.get("max_buffer_seconds", 300) * SAMPLE_RATE,
    }


def handle_client(conn, state, bus):
    engine = state["engine"]
    max_samples = state["max_buffer_samples"]
    lang = None
    if bus:
        bus.emit("stt.connection_open")

    try:
        # ── Language line ───────────────────────────────
        # First line is always a \n-terminated language tag (ISO 639-1).
        # Send just "\n" for default (no language hint).
        f = conn.makefile("rb")
        first = f.readline().decode().strip()
        if first:
            lang = first

        # ── Read raw PCM16 until EOF (SHUT_WR) ──────────
        # Read through the same BufferedReader so no bytes from readline() are lost.
        conn.settimeout(300)
        raw = f.read()
        conn.settimeout(None)
        f.close()
        if bus:
            bus.emit("stt.audio_chunk", bytes=len(raw))

        total_samples = len(raw) // 2
        if total_samples > max_samples:
            if bus:
                bus.emit("stt.buffer_reject", total_samples=total_samples, max_samples=max_samples)
            conn.sendall(json.dumps({"error": "buffer limit exceeded"}).encode())
            return

        if total_samples == 0:
            conn.sendall(json.dumps({"error": "no audio data"}).encode())
            return

        # ── Decode PCM16 → float32 ──────────────────────
        audio = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0

        # ── Transcribe ──────────────────────────────────
        if bus:
            bus.emit("stt.transcribe_start", samples=total_samples)
        t0 = time.time()
        segments, _ = engine.model.transcribe(
            audio, language=lang or None,
            beam_size=engine.beam_size, vad_filter=True,
        )
        elapsed = round(time.time() - t0, 2)
        result = [{"text": s.text.strip(), "start": s.start, "end": s.end} for s in segments]
        full = " ".join(s["text"] for s in result)
        dur = total_samples / SAMPLE_RATE
        if bus:
            bus.emit("stt.transcribe_done", text=full, duration=round(dur, 2), time_s=elapsed, segments=len(result))

        # ── Response ────────────────────────────────────
        conn.sendall(json.dumps({
            "text": full,
            "segments": result,
            "duration": round(dur, 2),
            "time_s": elapsed,
        }).encode())

    except Exception as e:
        print(f"[stt] ERROR: {e}", flush=True)
        if bus:
            bus.emit("stt.error", error=str(e))
        try:
            conn.sendall(json.dumps({"error": str(e)}).encode())
        except Exception:
            pass
    finally:
        if bus:
            bus.emit("stt.connection_close")
        conn.close()


if __name__ == "__main__":
    run_daemon(
        "STT",
        default_socket="/tmp/stt-daemon.sock",
        setup=setup,
        handle_client=handle_client,
        max_connections=config.get("max_connections", 4),
    )