#!/usr/bin/env python3
"""STT daemon — generated by daemon_builder."""

import base64
import io
import json
import os
import sys
import time

import numpy as np
import scipy.io.wavfile as wav

_DIR = os.path.dirname(os.path.abspath(__file__))
_ML = os.path.dirname(_DIR)
sys.path.insert(0, _DIR)
sys.path.insert(0, os.path.join(_ML, "daemon"))
sys.path.insert(0, os.path.join(_ML, "monitor"))

import config
from daemon_builder import run_daemon
from model import load_engine

SAMPLE_RATE = 16000


def decode_audio(raw, fmt):
    if fmt == "pcm16":
        return np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
    rate, arr = wav.read(io.BytesIO(raw))
    if arr.dtype == np.int16:
        arr = arr.astype(np.float32) / 32768.0
    return arr


def setup():
    engine = load_engine(
        model_size=config.get("model_size"),
        device=config.get("device"),
        compute_type=config.get("compute_type"),
        beam_size=config.get("beam_size"),
    )
    return {
        "engine": engine,
        "max_buffer_samples": config.get("max_buffer_seconds", 300) * SAMPLE_RATE,
    }


def handle_client(conn, state, bus):
    f = conn.makefile("rb")
    out = conn.makefile("wb")
    buffer = []
    total_samples = 0
    lang = None
    engine = state["engine"]
    max_samples = state["max_buffer_samples"]

    if bus:
        bus.emit("stt.connection_open")

    try:
        for line in f:
            if not line.strip():
                continue
            msg = json.loads(line.decode())
            cmd = msg.get("type")

            if cmd == "audio":
                raw = base64.b64decode(msg["data"])
                arr = decode_audio(raw, msg.get("format", "wav"))

                if total_samples + len(arr) > max_samples:
                    if bus:
                        bus.emit("stt.buffer_reject", total_samples=total_samples, max_samples=max_samples)
                    out.write(json.dumps({"type": "error", "message": "buffer limit exceeded"}).encode() + b"\n")
                    out.flush()
                    break

                buffer.append(arr)
                total_samples += len(arr)
                if bus:
                    bus.emit("stt.audio_chunk", samples=len(arr), total_samples=total_samples)

            elif cmd == "lang":
                lang = msg.get("lang", lang)

            elif cmd == "flush":
                audio = np.concatenate(buffer) if buffer else np.array([], dtype=np.float32)
                t0 = time.time()
                segments, _ = engine.model.transcribe(
                    audio, language=msg.get("lang", lang),
                    beam_size=engine.beam_size, vad_filter=True,
                )
                result = [{"text": s.text.strip(), "start": s.start, "end": s.end} for s in segments]
                full = " ".join(s["text"] for s in result)
                dur = len(audio) / SAMPLE_RATE
                elapsed = round(time.time() - t0, 2)
                print(f"Transcribed {dur:.1f}s in {elapsed}s: {full[:60]}...", flush=True)
                if bus:
                    bus.emit("stt.transcribe_done", text=full, duration=round(dur, 2), time_s=elapsed, segments=len(result))

                out.write(json.dumps({
                    "type": "done", "text": full, "segments": result,
                    "duration": round(dur, 2), "time_s": elapsed,
                }).encode() + b"\n")
                out.flush()
                break

            else:
                out.write(json.dumps({"type": "error", "message": f"unknown: {cmd}"}).encode() + b"\n")
                out.flush()
    except Exception:
        pass
    finally:
        if bus:
            bus.emit("stt.connection_close")
        f.close()
        out.close()
        conn.close()


if __name__ == "__main__":
    run_daemon(
        "STT",
        default_socket="/tmp/stt-daemon.sock",
        default_event_socket="/tmp/stt-events.sock",
        setup=setup,
        handle_client=handle_client,
        max_connections=config.get("max_connections", 4),
    )
