#!/usr/bin/env python3
"""TTS daemon — generated by daemon_builder. Streams raw PCM16 audio."""

import json
import os
import socket
import sys
import time

import numpy as np


_DIR = os.path.dirname(os.path.abspath(__file__))
_ML = os.path.dirname(_DIR)
sys.path.insert(0, _DIR)
sys.path.insert(0, os.path.join(_ML, "daemon"))

import config
from daemon_builder import run_daemon
from model import load_engine, create_session, load_voices_config, get_default_voice

SAMPLE_RATE = 24000


def setup():
    voices = load_voices_config()
    default_voice = get_default_voice(voices)
    if not default_voice:
        raise RuntimeError("No voices found in config")
    
    engine = load_engine(config.get("model_path"), verbose=config.get("verbose"))
    session = create_session(engine, default_voice)
    
    return {"session": session, "voices": voices}


def handle_client(conn, state, bus):
    session = state["session"]
    voices = state["voices"]

    # ── Read JSON command (client sends one line + SHUT_WR) ───
    conn.settimeout(300)
    f = conn.makefile("rb")
    bus.emit("tts.read_start")
    raw = f.read()
    bus.emit("tts.read_done", bytes=len(raw))
    conn.settimeout(None)
    f.close()

    line, _, _ = raw.partition(b"\n")
    if not line:
        return

    msg = json.loads(line.decode())
    cmd = msg.get("type")
    bus.emit("tts.command", command=cmd)

    if cmd == "synthesize":
        _handle_synthesize(conn, session, msg, bus)
    elif cmd == "voices":
        _handle_voices(conn, voices, bus)
    else:
        bus.emit("tts.unknown_command", command=cmd)


def _handle_synthesize(conn, session, msg, bus):
    text = msg.get("text", "").strip()
    if not text:
        bus.emit("tts.synthesize_error", error="text is required")
        return

    voice = msg.get("voice")
    lang = msg.get("lang")
    if voice or lang:
        session.configure(voice=voice, lang=lang)

    bus.emit("tts.synthesize_start", text=text, voice=voice, lang=lang)

    # ── Stream raw PCM16 ─────────────────────────────────────
    total_samples = 0
    t0 = time.time()
    sr = 24000

    for chunk in session.generate(text, lang_code=lang):
        audio = chunk["audio"]
        sr = chunk.get("sample_rate", sr)
        if audio.dtype == np.float32:
            audio = (audio * 32767).astype(np.int16)
        total_samples += len(audio)
        conn.sendall(audio.tobytes())
        bus.emit("tts.audio_chunk", bytes=len(audio), total_samples=total_samples)

    elapsed = round(time.time() - t0, 2)

    conn.shutdown(socket.SHUT_WR)
    bus.emit("tts.synthesize_done", text=text, samples=total_samples, sr=sr)


def _handle_voices(conn, voices, bus):
    conn.sendall(json.dumps({
        "voices": [
            {
                "name": v["name"],
                "description": v.get("description", ""),
                "languages": v.get("languages", [])
            }
            for v in voices
        ],
    }).encode() + b"\n")
    conn.shutdown(socket.SHUT_WR)
    bus.emit("tts.voices_listed", count=len(voices))


if __name__ == "__main__":
    run_daemon(
        "TTS",
        default_socket="/tmp/tts-daemon.sock",
        setup=setup,
        handle_client=handle_client,
    )
